package ds;


import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author chaosprince
 */
public class LoginSignupForm extends javax.swing.JFrame {
    
    private ClientData client;
    private Serializer save;

    /**
     * Creates new form NewJFrame
     */
    public LoginSignupForm() {
        initComponents();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
    
    public String getUsername(){
        return this.UsernameField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        SignupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login/Signup");
        setLocation(new java.awt.Point(400, 200));

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        UsernameField.setColumns(20);
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });

        PasswordField.setColumns(20);
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        SignupButton.setText("Signup");
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginButton)
                .addGap(31, 31, 31)
                .addComponent(SignupButton)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(SignupButton))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        //password textfield
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        //signup button
        String username = this.UsernameField.getText();
        String password = this.PasswordField.getText();
        if (username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid user name or password");
            return;
        }
        DBHandler checkclient = new DBHandler();
        checkclient.setQuery("SELECT `ID`, `Name`, `Password` FROM `clients` WHERE Name='" + username + "' AND Password='" + password + "';");
        ResultSet s = checkclient.executeQuery();
        try {
            boolean duplicate = s.next();
            if (duplicate) {
                JOptionPane.showMessageDialog(null, "Invalid user name or password(buplicated info)");
                return;
            } else {
                checkclient.setQuery("INSERT INTO `clients`(`Name`, `Password`) VALUES ('" + username + "','" + password + "');");
                checkclient.executeQuery();
                //Serialization
                checkclient.setQuery("SELECT `ID`, `Name`, `Password` FROM `clients` WHERE `Name`='"+username+"';");
                ResultSet t = checkclient.executeQuery();
                t.next();
                client = new ClientData(t.getInt("ID"), t.getString("Name"), t.getString("Password"));
                save = new Serializer();
                save.setFilename("client");
                save.setLocation(System.getProperty("user.home"));
                save.serialize(client);
                //JOptionPane.showMessageDialog(null, "successful register.");
                //here should go to form 2
                new WelcomeForm(username).setVisible(true);
                //try {
                    //goto form 2,special case for admin
                    //using RMI to do so and distinguish between an amdin and a client..!!!!
                //    ServerI obj = (ServerI) Naming.lookup("login");
                //    obj.login(username);
                //} catch (NotBoundException | MalformedURLException | RemoteException ex) {
                  //  JOptionPane.showMessageDialog(null, "Out Of Service(faild)."+ex.getMessage());
                //}
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        checkclient.endDBConnection();
        this.dispose();
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        //username textfield
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        //login button
        String username = this.UsernameField.getText();
        String password = this.PasswordField.getText();
        if (username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid user name or password");
            return;
        }
        DBHandler checkclient = new DBHandler();
        checkclient.setQuery("SELECT `ID`, `Name`, `Password` FROM `clients` WHERE Name='" + username + "' AND Password='" + password + "';");
        ResultSet userexists = checkclient.executeQuery();
        try {
            userexists.next();//this means the first row,since the reslut should be a single row
            String username2 = userexists.getString(2);
            String password2 = userexists.getString(3);
            if (username2.equals(username) && password2.equals(password)) {
                //try {
                    //goto form 2,special case for admin
                    //using RMI to do so and distinguish between an amdin and a client..!!!!
                  //  ServerI obj = (ServerI) Naming.lookup("login");
                    //obj.login(username);
                //} catch (NotBoundException | MalformedURLException | RemoteException ex) {
                  //  JOptionPane.showMessageDialog(null, "Out Of Sservice(faild)."+ex.getMessage());
                //}
                //JOptionPane.showMessageDialog(null, "Success login.");
                if(username.toLowerCase().equals("admin")){
                    new AdminForm().setVisible(true);
                }else{
                    new WelcomeForm(username).setVisible(true);
                }
                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, "Invalid user name or password");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Invalid user name or password");
        }
        checkclient.endDBConnection();
        this.dispose();//destroys the jframe object
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new LoginSignupForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JButton SignupButton;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
